-- ============================================================
-- GSO PRIMS — Sprint 11 fix-up (idempotent, safe to run repeatedly)
-- Re-applies parts the first run may have skipped: stock card +
-- audit seeds, counters, storage bucket & policies, realtime,
-- and the audit triggers.
-- ============================================================

-- counters (no-op when already present)
insert into public.doc_counters (prefix, next_no) values ('PR', 216), ('PO', 119), ('RIS', 319), ('FR', 442)
on conflict (prefix) do nothing;

-- stock_card
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-17$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-1$sq$, $sq$Bond paper A4 70gsm$sq$, 300, 0, 300, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-18$sq$, $sq$2026-07-12T09:00:00+08:00$sq$, $sq$PO-2026-0114$sq$, $sq$Purchase Order$sq$, $sq$inv-1$sq$, $sq$Bond paper A4 70gsm$sq$, 250, 0, 550, $sq$Delivery received in full$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-19$sq$, $sq$2026-07-14T09:00:00+08:00$sq$, $sq$RIS-2026-0314$sq$, $sq$RIS Release$sq$, $sq$inv-1$sq$, $sq$Bond paper A4 70gsm$sq$, 0, 25, 525, $sq$Issued to Budget Office$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-20$sq$, $sq$2026-07-15T09:00:00+08:00$sq$, $sq$RIS-2026-0312$sq$, $sq$RIS Release$sq$, $sq$inv-1$sq$, $sq$Bond paper A4 70gsm$sq$, 0, 30, 495, $sq$Issued to Planning Office$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-21$sq$, $sq$2026-07-16T09:00:00+08:00$sq$, $sq$ADJ-2026-0021$sq$, $sq$Manual Adjustment$sq$, $sq$inv-1$sq$, $sq$Bond paper A4 70gsm$sq$, 0, 12, 483, $sq$Water-damaged reams disposed$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-22$sq$, $sq$2026-07-17T09:00:00+08:00$sq$, $sq$COR-2026-0007$sq$, $sq$Correction$sq$, $sq$inv-1$sq$, $sq$Bond paper A4 70gsm$sq$, 0, 3, 480, $sq$Count reconciliation vs physical inventory$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-23$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-4$sq$, $sq$Printer toner, high yield$sq$, 14, 0, 14, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-24$sq$, $sq$2026-07-09T09:00:00+08:00$sq$, $sq$PO-2026-0112$sq$, $sq$Purchase Order$sq$, $sq$inv-4$sq$, $sq$Printer toner, high yield$sq$, 6, 0, 20, $sq$Delivery received in full$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-25$sq$, $sq$2026-07-10T09:00:00+08:00$sq$, $sq$RIS-2026-0312$sq$, $sq$RIS Release$sq$, $sq$inv-4$sq$, $sq$Printer toner, high yield$sq$, 0, 2, 18, $sq$Issued to Planning Office$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-26$sq$, $sq$2026-07-11T09:00:00+08:00$sq$, $sq$RET-2026-0003$sq$, $sq$Return$sq$, $sq$inv-4$sq$, $sq$Printer toner, high yield$sq$, 1, 0, 19, $sq$Unused cartridge returned by MPDO$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-27$sq$, $sq$2026-07-12T09:00:00+08:00$sq$, $sq$RIS-2026-0309$sq$, $sq$RIS Release$sq$, $sq$inv-4$sq$, $sq$Printer toner, high yield$sq$, 0, 1, 18, $sq$Issued to Accounting Office$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-28$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-7$sq$, $sq$Disinfectant solution, 1 gal$sq$, 28, 0, 28, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-29$sq$, $sq$2026-07-12T09:00:00+08:00$sq$, $sq$RIS-2026-0313$sq$, $sq$RIS Release$sq$, $sq$inv-7$sq$, $sq$Disinfectant solution, 1 gal$sq$, 0, 4, 24, $sq$Issued to MSWDO feeding stations$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-30$sq$, $sq$2026-07-15T09:00:00+08:00$sq$, $sq$PO-2026-0116$sq$, $sq$Purchase Order$sq$, $sq$inv-7$sq$, $sq$Disinfectant solution, 1 gal$sq$, 12, 0, 36, $sq$Delivery received in full$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-31$sq$, $sq$2026-07-16T09:00:00+08:00$sq$, $sq$ADJ-2026-0022$sq$, $sq$Manual Adjustment$sq$, $sq$inv-7$sq$, $sq$Disinfectant solution, 1 gal$sq$, 0, 4, 32, $sq$Leaking container disposed$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-32$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-9$sq$, $sq$Alcohol 70% isopropyl, 1 gal$sq$, 24, 0, 24, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-33$sq$, $sq$2026-07-08T09:00:00+08:00$sq$, $sq$RIS-2026-0311$sq$, $sq$RIS Release$sq$, $sq$inv-9$sq$, $sq$Alcohol 70% isopropyl, 1 gal$sq$, 0, 4, 20, $sq$Issued to RHU dental clinic$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-34$sq$, $sq$2026-07-10T09:00:00+08:00$sq$, $sq$PO-2026-0111$sq$, $sq$Purchase Order$sq$, $sq$inv-9$sq$, $sq$Alcohol 70% isopropyl, 1 gal$sq$, 6, 0, 26, $sq$Delivery received in full$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-35$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-14$sq$, $sq$Battery AA alkaline (24s)$sq$, 12, 0, 12, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-36$sq$, $sq$2026-07-11T09:00:00+08:00$sq$, $sq$RIS-2026-0305$sq$, $sq$RIS Release$sq$, $sq$inv-14$sq$, $sq$Battery AA alkaline (24s)$sq$, 0, 8, 4, $sq$Issued to MDRRMO radios$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-37$sq$, $sq$2026-07-16T09:00:00+08:00$sq$, $sq$COR-2026-0008$sq$, $sq$Correction$sq$, $sq$inv-14$sq$, $sq$Battery AA alkaline (24s)$sq$, 0, 1, 3, $sq$Count reconciliation vs physical inventory$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-38$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-13$sq$, $sq$Ink cartridge, black (inkjet)$sq$, 6, 0, 6, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-39$sq$, $sq$2026-07-09T09:00:00+08:00$sq$, $sq$RIS-2026-0304$sq$, $sq$RIS Release$sq$, $sq$inv-13$sq$, $sq$Ink cartridge, black (inkjet)$sq$, 0, 6, 0, $sq$Issued to Mayor's Office$sq$, $sq$Mr. Danilo Reyes$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-40$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-2$sq$, $sq$Bond paper Legal 70gsm$sq$, 260, 0, 260, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-41$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-3$sq$, $sq$Ballpen black 0.5 (50s)$sq$, 54, 0, 54, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-42$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-5$sq$, $sq$Folder legal, kraft (100s)$sq$, 35, 0, 35, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-43$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-6$sq$, $sq$Staple wire #35$sq$, 96, 0, 96, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-44$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-8$sq$, $sq$Trash bags XL (100s)$sq$, 44, 0, 44, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-45$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-10$sq$, $sq$First aid kit, standard$sq$, 9, 0, 9, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-46$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-11$sq$, $sq$Archival storage boxes$sq$, 120, 0, 120, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-47$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-12$sq$, $sq$Hand soap refill 5L$sq$, 21, 0, 21, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-48$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-15$sq$, $sq$Whiteboard marker (12s)$sq$, 8, 0, 8, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
insert into public.stock_card (id, date, document_number, type, item_id, item_name, quantity_in, quantity_out, balance, remarks, user_name) values ($sq$inv-seed-49$sq$, $sq$2026-07-01T09:00:00+08:00$sq$, $sq$FY26-OPEN$sq$, $sq$Beginning Balance$sq$, $sq$inv-16$sq$, $sq$Portland cement, 40kg$sq$, 150, 0, 150, $sq$Fiscal year opening balance$sq$, $sq$Marites Villanueva$sq$) on conflict (id) do nothing;
-- audit_logs
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0015$sq$, $sq$2026-07-19T13:20:00+08:00$sq$, $sq$Administrator$sq$, $sq$System Administrator$sq$, $sq$GSO$sq$, $sq$System$sq$, $sq$Settings Updated$sq$, $sq$SYS-CONFIG$sq$, $sq$BAC threshold: ₱50,000$sq$, $sq$BAC threshold: ₱100,000$sq$, $sq$Approval routing rules changed$sq$, $sq$Per SB Resolution 2026-118$sq$, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0719-01$sq$, $sq$Critical$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0014$sq$, $sq$2026-07-19T11:47:00+08:00$sq$, $sq$Mr. Nestor Abad$sq$, $sq$Budget Officer$sq$, $sq$MBO$sq$, $sq$Purchase Requests$sq$, $sq$Create Purchase Request$sq$, $sq$PR-2026-0215$sq$, null, null, $sq$Draft created$sq$, null, $sq$192.168.10.12$sq$, $sq$Firefox 127$sq$, $sq$Windows 11$sq$, $sq$SES-0719-08$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0013$sq$, $sq$2026-07-19T11:04:00+08:00$sq$, $sq$Administrator$sq$, $sq$System Administrator$sq$, $sq$GSO$sq$, $sq$Reports$sq$, $sq$Report Exported$sq$, $sq$PR-REPORT$sq$, null, null, $sq$CSV exported (28 rows)$sq$, null, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0719-01$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0012$sq$, $sq$2026-07-19T11:02:00+08:00$sq$, $sq$Administrator$sq$, $sq$System Administrator$sq$, $sq$GSO$sq$, $sq$Reports$sq$, $sq$Report Generated$sq$, $sq$PR-REPORT$sq$, null, null, $sq$Purchase Request Report · 28 records$sq$, null, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0719-01$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0011$sq$, $sq$2026-07-19T10:31:00+08:00$sq$, $sq$Engr. Paolo Madrigal$sq$, $sq$GSO Head$sq$, $sq$GSO$sq$, $sq$Reservations$sq$, $sq$Reservation Approved$sq$, $sq$FR-2026-0431$sq$, $sq$Status: Pending$sq$, $sq$Status: Approved$sq$, $sq$Time slot blocked$sq$, null, $sq$192.168.10.12$sq$, $sq$Firefox 127$sq$, $sq$Windows 11$sq$, $sq$SES-0719-03$sq$, $sq$Success$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0010$sq$, $sq$2026-07-19T10:15:00+08:00$sq$, $sq$Ms. Liza Reyes$sq$, $sq$Social Welfare Officer$sq$, $sq$MSWDO$sq$, $sq$Reservations$sq$, $sq$Reservation Created$sq$, $sq$FR-2026-0433$sq$, null, null, $sq$Reservation submitted for approval$sq$, null, $sq$192.168.10.34$sq$, $sq$Edge 125$sq$, $sq$Windows 10$sq$, $sq$SES-0719-07$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0009$sq$, $sq$2026-07-19T09:49:00+08:00$sq$, $sq$Mr. Danilo Reyes$sq$, $sq$Storekeeper$sq$, $sq$GSO$sq$, $sq$Inventory$sq$, $sq$Stock Movement$sq$, $sq$RIS-2026-0316$sq$, null, null, $sq$Stock card updated (−50 units)$sq$, null, $sq$192.168.10.55$sq$, $sq$Chrome 126$sq$, $sq$macOS 14$sq$, $sq$SES-0719-04$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0008$sq$, $sq$2026-07-19T09:48:00+08:00$sq$, $sq$Mr. Danilo Reyes$sq$, $sq$Storekeeper$sq$, $sq$GSO$sq$, $sq$RIS$sq$, $sq$Release RIS$sq$, $sq$RIS-2026-0316$sq$, $sq$Status: Approved$sq$, $sq$Status: Released$sq$, $sq$Stock deducted · 2 stock card entries created$sq$, null, $sq$192.168.10.55$sq$, $sq$Chrome 126$sq$, $sq$macOS 14$sq$, $sq$SES-0719-04$sq$, $sq$Success$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0007$sq$, $sq$2026-07-19T09:22:00+08:00$sq$, $sq$Marites Villanueva$sq$, $sq$Supply Officer$sq$, $sq$GSO$sq$, $sq$RIS$sq$, $sq$Approve RIS$sq$, $sq$RIS-2026-0317$sq$, $sq$Status: Pending Approval$sq$, $sq$Status: Approved$sq$, $sq$Workflow advanced$sq$, null, $sq$192.168.10.34$sq$, $sq$Edge 125$sq$, $sq$Windows 10$sq$, $sq$SES-0719-02$sq$, $sq$Success$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0006$sq$, $sq$2026-07-19T09:05:00+08:00$sq$, $sq$Engr. Paolo Madrigal$sq$, $sq$GSO Head$sq$, $sq$GSO$sq$, $sq$Purchase Requests$sq$, $sq$Approve Purchase Request$sq$, $sq$PR-2026-0210$sq$, $sq$Status: Submitted$sq$, $sq$Status: Department Head Review$sq$, $sq$Workflow advanced$sq$, null, $sq$192.168.10.12$sq$, $sq$Firefox 127$sq$, $sq$Windows 11$sq$, $sq$SES-0719-03$sq$, $sq$Success$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0005$sq$, $sq$2026-07-19T08:40:00+08:00$sq$, $sq$Dr. Rowena Salazar$sq$, $sq$Municipal Health Officer$sq$, $sq$MHO$sq$, $sq$Purchase Requests$sq$, $sq$Update Purchase Request$sq$, $sq$PR-2026-0214$sq$, $sq$Items: 3$sq$, $sq$Items: 4$sq$, $sq$Record saved$sq$, null, $sq$10.10.2.18$sq$, $sq$Safari 17$sq$, $sq$Windows 11$sq$, $sq$SES-0719-05$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0004$sq$, $sq$2026-07-19T08:12:00+08:00$sq$, $sq$Dr. Rowena Salazar$sq$, $sq$Municipal Health Officer$sq$, $sq$MHO$sq$, $sq$Authentication$sq$, $sq$Login$sq$, null, null, null, $sq$Session established$sq$, null, $sq$10.10.2.18$sq$, $sq$Safari 17$sq$, $sq$Windows 11$sq$, $sq$SES-0719-05$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0003$sq$, $sq$2026-07-19T08:11:00+08:00$sq$, $sq$Dr. Rowena Salazar$sq$, $sq$Municipal Health Officer$sq$, $sq$MHO$sq$, $sq$Authentication$sq$, $sq$Failed Login$sq$, null, null, null, $sq$Invalid credentials (attempt 2 of 5)$sq$, $sq$Password mismatch from RHU workstation$sq$, $sq$10.10.2.18$sq$, $sq$Safari 17$sq$, $sq$Windows 11$sq$, $sq$SES-0719-05$sq$, $sq$Error$sq$, $sq$Failed$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0002$sq$, $sq$2026-07-19T08:03:00+08:00$sq$, $sq$Marites Villanueva$sq$, $sq$Supply Officer$sq$, $sq$GSO$sq$, $sq$Authentication$sq$, $sq$Login$sq$, null, null, null, $sq$Session established$sq$, null, $sq$192.168.10.34$sq$, $sq$Edge 125$sq$, $sq$Windows 10$sq$, $sq$SES-0719-02$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0001$sq$, $sq$2026-07-19T07:58:00+08:00$sq$, $sq$Administrator$sq$, $sq$System Administrator$sq$, $sq$GSO$sq$, $sq$Authentication$sq$, $sq$Login$sq$, null, null, null, $sq$Session established$sq$, null, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0719-01$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0025$sq$, $sq$2026-07-18T16:58:00+08:00$sq$, $sq$Administrator$sq$, $sq$System Administrator$sq$, $sq$GSO$sq$, $sq$Authentication$sq$, $sq$Logout$sq$, null, null, null, $sq$Session closed$sq$, null, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0718-01$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0024$sq$, $sq$2026-07-18T15:33:00+08:00$sq$, $sq$Administrator$sq$, $sq$System Administrator$sq$, $sq$GSO$sq$, $sq$System$sq$, $sq$User Updated$sq$, $sq$USR-0009$sq$, $sq$Role: Clerk$sq$, $sq$Role: Treasurer$sq$, $sq$Account updated$sq$, null, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0718-01$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0023$sq$, $sq$2026-07-18T14:08:00+08:00$sq$, $sq$Ms. Gloria Santiago$sq$, $sq$Treasurer$sq$, $sq$TRE$sq$, $sq$Authentication$sq$, $sq$Login$sq$, null, null, null, $sq$Session established$sq$, null, $sq$192.168.10.55$sq$, $sq$Chrome 126$sq$, $sq$macOS 14$sq$, $sq$SES-0718-09$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0022$sq$, $sq$2026-07-18T14:07:00+08:00$sq$, $sq$Ms. Gloria Santiago$sq$, $sq$Treasurer$sq$, $sq$TRE$sq$, $sq$Authentication$sq$, $sq$Failed Login$sq$, null, null, null, $sq$Invalid credentials (attempt 1 of 5)$sq$, null, $sq$192.168.10.55$sq$, $sq$Chrome 126$sq$, $sq$macOS 14$sq$, $sq$SES-0718-09$sq$, $sq$Warning$sq$, $sq$Failed$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0021$sq$, $sq$2026-07-18T11:25:00+08:00$sq$, $sq$Marites Villanueva$sq$, $sq$Supply Officer$sq$, $sq$GSO$sq$, $sq$RIS$sq$, $sq$Create RIS$sq$, $sq$RIS-2026-0318$sq$, null, null, $sq$Slip submitted for approval$sq$, null, $sq$192.168.10.34$sq$, $sq$Edge 125$sq$, $sq$Windows 10$sq$, $sq$SES-0718-02$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0020$sq$, $sq$2026-07-18T10:12:00+08:00$sq$, $sq$Mr. Danilo Reyes$sq$, $sq$Storekeeper$sq$, $sq$GSO$sq$, $sq$Inventory$sq$, $sq$Inventory Adjustment$sq$, $sq$ADJ-2026-0021$sq$, $sq$On hand: 495$sq$, $sq$On hand: 483$sq$, $sq$Stock reduced (−12 reams)$sq$, $sq$Water-damaged reams disposed$sq$, $sq$192.168.10.55$sq$, $sq$Chrome 126$sq$, $sq$macOS 14$sq$, $sq$SES-0718-04$sq$, $sq$Warning$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0019$sq$, $sq$2026-07-18T09:30:00+08:00$sq$, $sq$Engr. Paolo Madrigal$sq$, $sq$GSO Head$sq$, $sq$GSO$sq$, $sq$Purchase Orders$sq$, $sq$Approve Purchase Order$sq$, $sq$PO-2026-0117$sq$, $sq$Status: Pending Approval$sq$, $sq$Status: Approved$sq$, $sq$Workflow advanced$sq$, null, $sq$192.168.10.12$sq$, $sq$Firefox 127$sq$, $sq$Windows 11$sq$, $sq$SES-0718-03$sq$, $sq$Success$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0018$sq$, $sq$2026-07-18T08:45:00+08:00$sq$, $sq$Engr. Jerome Cruz$sq$, $sq$Project Engineer$sq$, $sq$ENG$sq$, $sq$Purchase Orders$sq$, $sq$Create Purchase Order$sq$, $sq$PO-2026-0118$sq$, null, null, $sq$Order drafted from PR-2026-0212$sq$, null, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0718-06$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0017$sq$, $sq$2026-07-18T08:06:00+08:00$sq$, $sq$Ms. Gloria Santiago$sq$, $sq$Treasurer$sq$, $sq$TRE$sq$, $sq$Authentication$sq$, $sq$Login$sq$, null, null, null, $sq$Session established$sq$, null, $sq$192.168.10.55$sq$, $sq$Chrome 126$sq$, $sq$macOS 14$sq$, $sq$SES-0718-09$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0016$sq$, $sq$2026-07-18T08:01:00+08:00$sq$, $sq$Administrator$sq$, $sq$System Administrator$sq$, $sq$GSO$sq$, $sq$Authentication$sq$, $sq$Login$sq$, null, null, null, $sq$Session established$sq$, null, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0718-01$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0031$sq$, $sq$2026-07-17T16:45:00+08:00$sq$, $sq$Administrator$sq$, $sq$System Administrator$sq$, $sq$GSO$sq$, $sq$System$sq$, $sq$Backup Completed$sq$, $sq$BAK-2026-0199$sq$, null, null, $sq$Nightly backup finished (2.4 GB)$sq$, null, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0717-01$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0030$sq$, $sq$2026-07-17T13:11:00+08:00$sq$, $sq$Mr. Danilo Reyes$sq$, $sq$Storekeeper$sq$, $sq$GSO$sq$, $sq$Inventory$sq$, $sq$Item Registered$sq$, $sq$CON-0001$sq$, null, null, $sq$Item added with beginning balance 150$sq$, null, $sq$192.168.10.55$sq$, $sq$Chrome 126$sq$, $sq$macOS 14$sq$, $sq$SES-0717-04$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0029$sq$, $sq$2026-07-17T10:20:00+08:00$sq$, $sq$Marites Villanueva$sq$, $sq$Supply Officer$sq$, $sq$GSO$sq$, $sq$Purchase Requests$sq$, $sq$Reject Purchase Request$sq$, $sq$PR-2026-0208$sq$, $sq$Status: Budget Review$sq$, $sq$Status: Rejected$sq$, $sq$Returned to requester$sq$, $sq$No remaining representation allocation$sq$, $sq$192.168.10.34$sq$, $sq$Edge 125$sq$, $sq$Windows 10$sq$, $sq$SES-0717-02$sq$, $sq$Warning$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0028$sq$, $sq$2026-07-17T09:40:00+08:00$sq$, $sq$Ms. Liza Reyes$sq$, $sq$Social Welfare Officer$sq$, $sq$MSWDO$sq$, $sq$Reservations$sq$, $sq$Reservation Cancelled$sq$, $sq$FR-2026-0430$sq$, $sq$Status: Approved$sq$, $sq$Status: Cancelled$sq$, $sq$Schedule freed$sq$, $sq$Cancelled at requester's advice$sq$, $sq$192.168.10.34$sq$, $sq$Edge 125$sq$, $sq$Windows 10$sq$, $sq$SES-0717-07$sq$, $sq$Warning$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0027$sq$, $sq$2026-07-17T08:55:00+08:00$sq$, $sq$Engr. Paolo Madrigal$sq$, $sq$GSO Head$sq$, $sq$GSO$sq$, $sq$Reservations$sq$, $sq$Reservation Approved$sq$, $sq$FR-2026-0434$sq$, $sq$Status: Pending$sq$, $sq$Status: Approved$sq$, $sq$Time slot blocked$sq$, null, $sq$192.168.10.12$sq$, $sq$Firefox 127$sq$, $sq$Windows 11$sq$, $sq$SES-0717-03$sq$, $sq$Success$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0026$sq$, $sq$2026-07-17T08:02:00+08:00$sq$, $sq$Engr. Paolo Madrigal$sq$, $sq$GSO Head$sq$, $sq$GSO$sq$, $sq$Authentication$sq$, $sq$Login$sq$, null, null, null, $sq$Session established$sq$, null, $sq$192.168.10.12$sq$, $sq$Firefox 127$sq$, $sq$Windows 11$sq$, $sq$SES-0717-03$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0037$sq$, $sq$2026-07-16T14:31:00+08:00$sq$, $sq$Mr. Danilo Reyes$sq$, $sq$Storekeeper$sq$, $sq$GSO$sq$, $sq$Inventory$sq$, $sq$Stock Movement$sq$, $sq$RIS-2026-0313$sq$, null, null, $sq$Stock card updated (−7 units)$sq$, null, $sq$192.168.10.55$sq$, $sq$Chrome 126$sq$, $sq$macOS 14$sq$, $sq$SES-0716-04$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0036$sq$, $sq$2026-07-16T14:30:00+08:00$sq$, $sq$Mr. Danilo Reyes$sq$, $sq$Storekeeper$sq$, $sq$GSO$sq$, $sq$RIS$sq$, $sq$Release RIS$sq$, $sq$RIS-2026-0313$sq$, $sq$Status: Approved$sq$, $sq$Status: Released$sq$, $sq$Stock deducted · 2 stock card entries created$sq$, null, $sq$192.168.10.55$sq$, $sq$Chrome 126$sq$, $sq$macOS 14$sq$, $sq$SES-0716-04$sq$, $sq$Success$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0035$sq$, $sq$2026-07-16T11:00:00+08:00$sq$, $sq$Administrator$sq$, $sq$System Administrator$sq$, $sq$GSO$sq$, $sq$System$sq$, $sq$Record Deleted$sq$, $sq$PR-2026-0148$sq$, $sq$Status: Draft$sq$, $sq$—$sq$, $sq$Draft purged by administrator$sq$, $sq$Duplicate draft removed on request$sq$, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0716-01$sq$, $sq$Critical$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0034$sq$, $sq$2026-07-16T10:44:00+08:00$sq$, $sq$Dr. Rowena Salazar$sq$, $sq$Municipal Health Officer$sq$, $sq$MHO$sq$, $sq$Authentication$sq$, $sq$Failed Login$sq$, null, null, null, $sq$Invalid credentials (attempt 3 of 5)$sq$, $sq$Account temporarily locked for 15 minutes$sq$, $sq$10.10.2.18$sq$, $sq$Safari 17$sq$, $sq$Windows 11$sq$, $sq$SES-0716-05$sq$, $sq$Error$sq$, $sq$Failed$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0033$sq$, $sq$2026-07-16T09:02:00+08:00$sq$, $sq$Engr. Jerome Cruz$sq$, $sq$Project Engineer$sq$, $sq$ENG$sq$, $sq$Purchase Requests$sq$, $sq$Create Purchase Request$sq$, $sq$PR-2026-0213$sq$, null, null, $sq$Request submitted$sq$, null, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0716-06$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0032$sq$, $sq$2026-07-16T08:15:00+08:00$sq$, $sq$Engr. Jerome Cruz$sq$, $sq$Project Engineer$sq$, $sq$ENG$sq$, $sq$Authentication$sq$, $sq$Login$sq$, null, null, null, $sq$Session established$sq$, null, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0716-06$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0040$sq$, $sq$2026-07-15T13:52:00+08:00$sq$, $sq$Administrator$sq$, $sq$System Administrator$sq$, $sq$GSO$sq$, $sq$Reports$sq$, $sq$Report Generated$sq$, $sq$VAL-REPORT$sq$, null, null, $sq$Inventory Valuation Report · 16 records$sq$, null, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0715-01$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0039$sq$, $sq$2026-07-15T09:27:00+08:00$sq$, $sq$Marites Villanueva$sq$, $sq$Supply Officer$sq$, $sq$GSO$sq$, $sq$Purchase Orders$sq$, $sq$Release Purchase Order$sq$, $sq$PO-2026-0116$sq$, $sq$Status: Approved$sq$, $sq$Status: Released$sq$, $sq$Order released to supplier$sq$, null, $sq$192.168.10.34$sq$, $sq$Edge 125$sq$, $sq$Windows 10$sq$, $sq$SES-0715-02$sq$, $sq$Success$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0038$sq$, $sq$2026-07-15T08:09:00+08:00$sq$, $sq$Marites Villanueva$sq$, $sq$Supply Officer$sq$, $sq$GSO$sq$, $sq$Authentication$sq$, $sq$Login$sq$, null, null, null, $sq$Session established$sq$, null, $sq$192.168.10.34$sq$, $sq$Edge 125$sq$, $sq$Windows 10$sq$, $sq$SES-0715-02$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0043$sq$, $sq$2026-07-14T10:05:00+08:00$sq$, $sq$Administrator$sq$, $sq$System Administrator$sq$, $sq$GSO$sq$, $sq$System$sq$, $sq$User Created$sq$, $sq$USR-0012$sq$, null, null, $sq$Account provisioned for MDRRMO clerk$sq$, null, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0714-01$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0042$sq$, $sq$2026-07-14T09:15:00+08:00$sq$, $sq$Mr. Nestor Abad$sq$, $sq$Budget Officer$sq$, $sq$MBO$sq$, $sq$Purchase Requests$sq$, $sq$Update Purchase Request$sq$, $sq$PR-2026-0203$sq$, $sq$Items: 2$sq$, $sq$Items: 3$sq$, $sq$Record saved$sq$, null, $sq$192.168.10.12$sq$, $sq$Firefox 127$sq$, $sq$Windows 11$sq$, $sq$SES-0714-08$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0041$sq$, $sq$2026-07-14T08:30:00+08:00$sq$, $sq$Mr. Nestor Abad$sq$, $sq$Budget Officer$sq$, $sq$MBO$sq$, $sq$Authentication$sq$, $sq$Login$sq$, null, null, null, $sq$Session established$sq$, null, $sq$192.168.10.12$sq$, $sq$Firefox 127$sq$, $sq$Windows 11$sq$, $sq$SES-0714-08$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0046$sq$, $sq$2026-07-13T15:40:00+08:00$sq$, $sq$Mr. Danilo Reyes$sq$, $sq$Storekeeper$sq$, $sq$GSO$sq$, $sq$Inventory$sq$, $sq$Inventory Adjustment$sq$, $sq$COR-2026-0007$sq$, $sq$On hand: 483$sq$, $sq$On hand: 480$sq$, $sq$Count reconciliation (−3 reams)$sq$, null, $sq$192.168.10.55$sq$, $sq$Chrome 126$sq$, $sq$macOS 14$sq$, $sq$SES-0713-04$sq$, $sq$Warning$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0045$sq$, $sq$2026-07-13T09:58:00+08:00$sq$, $sq$Engr. Paolo Madrigal$sq$, $sq$GSO Head$sq$, $sq$GSO$sq$, $sq$Purchase Orders$sq$, $sq$Approve Purchase Order$sq$, $sq$PO-2026-0115$sq$, $sq$Status: Pending Approval$sq$, $sq$Status: Approved$sq$, $sq$Workflow advanced$sq$, null, $sq$192.168.10.12$sq$, $sq$Firefox 127$sq$, $sq$Windows 11$sq$, $sq$SES-0713-03$sq$, $sq$Success$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0044$sq$, $sq$2026-07-13T08:44:00+08:00$sq$, $sq$Engr. Paolo Madrigal$sq$, $sq$GSO Head$sq$, $sq$GSO$sq$, $sq$Authentication$sq$, $sq$Login$sq$, null, null, null, $sq$Session established$sq$, null, $sq$192.168.10.12$sq$, $sq$Firefox 127$sq$, $sq$Windows 11$sq$, $sq$SES-0713-03$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0049$sq$, $sq$2026-07-12T11:20:00+08:00$sq$, $sq$Administrator$sq$, $sq$System Administrator$sq$, $sq$GSO$sq$, $sq$System$sq$, $sq$Settings Updated$sq$, $sq$SYS-CONFIG$sq$, $sq$smtp.old.local$sq$, $sq$smtp.alaminos.gov.ph$sq$, $sq$SMTP relay endpoint changed$sq$, null, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0712-01$sq$, $sq$Warning$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0048$sq$, $sq$2026-07-12T10:33:00+08:00$sq$, $sq$Ms. Gloria Santiago$sq$, $sq$Treasurer$sq$, $sq$TRE$sq$, $sq$Reports$sq$, $sq$Report Exported$sq$, $sq$STOCK-CARD$sq$, null, null, $sq$PDF generated (42 rows)$sq$, null, $sq$192.168.10.55$sq$, $sq$Chrome 126$sq$, $sq$macOS 14$sq$, $sq$SES-0712-09$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0047$sq$, $sq$2026-07-12T08:12:00+08:00$sq$, $sq$Ms. Gloria Santiago$sq$, $sq$Treasurer$sq$, $sq$TRE$sq$, $sq$Authentication$sq$, $sq$Login$sq$, null, null, null, $sq$Session established$sq$, null, $sq$192.168.10.55$sq$, $sq$Chrome 126$sq$, $sq$macOS 14$sq$, $sq$SES-0712-09$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0050$sq$, $sq$2026-07-11T09:05:00+08:00$sq$, $sq$Ms. Liza Reyes$sq$, $sq$Social Welfare Officer$sq$, $sq$MSWDO$sq$, $sq$Reservations$sq$, $sq$Reservation Created$sq$, $sq$FR-2026-0429$sq$, null, null, $sq$Reservation submitted for approval$sq$, null, $sq$192.168.10.34$sq$, $sq$Edge 125$sq$, $sq$Windows 10$sq$, $sq$SES-0711-07$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0051$sq$, $sq$2026-07-10T08:20:00+08:00$sq$, $sq$Dr. Rowena Salazar$sq$, $sq$Municipal Health Officer$sq$, $sq$MHO$sq$, $sq$RIS$sq$, $sq$Create RIS$sq$, $sq$RIS-2026-0315$sq$, null, null, $sq$Slip submitted for approval$sq$, null, $sq$10.10.2.18$sq$, $sq$Safari 17$sq$, $sq$Windows 11$sq$, $sq$SES-0710-05$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0052$sq$, $sq$2026-07-09T13:44:00+08:00$sq$, $sq$Engr. Jerome Cruz$sq$, $sq$Project Engineer$sq$, $sq$ENG$sq$, $sq$Purchase Orders$sq$, $sq$Create Purchase Order$sq$, $sq$PO-2026-0113$sq$, null, null, $sq$Order drafted from PR-2026-0204$sq$, null, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0709-06$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0053$sq$, $sq$2026-07-08T09:31:00+08:00$sq$, $sq$Administrator$sq$, $sq$System Administrator$sq$, $sq$GSO$sq$, $sq$System$sq$, $sq$Backup Completed$sq$, $sq$BAK-2026-0195$sq$, null, null, $sq$Nightly backup finished (2.3 GB)$sq$, null, $sq$192.168.10.21$sq$, $sq$Chrome 126$sq$, $sq$Windows 11$sq$, $sq$SES-0708-01$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;
insert into public.audit_logs (id, timestamp, user_name, user_role, department_code, module, action, document_number, previous_value, updated_value, response, remarks, ip, browser, os, session_id, severity, status, comments) values ($sq$AUD-2026-0054$sq$, $sq$2026-07-07T10:02:00+08:00$sq$, $sq$Marites Villanueva$sq$, $sq$Supply Officer$sq$, $sq$GSO$sq$, $sq$Inventory$sq$, $sq$Stock Movement$sq$, $sq$PO-2026-0114$sq$, null, null, $sq$Delivery received (+250 reams)$sq$, null, $sq$192.168.10.34$sq$, $sq$Edge 125$sq$, $sq$Windows 10$sq$, $sq$SES-0707-02$sq$, $sq$Information$sq$, $sq$Success$sq$, $sq$[]$sq$::jsonb) on conflict (id) do nothing;

-- storage bucket + policies (each guarded)
insert into storage.buckets (id, name, public) values ('attachments', 'attachments', true)
on conflict (id) do nothing;

do $$ begin
  create policy attachments_read on storage.objects for select using (bucket_id = 'attachments');
exception when others then null; end $$;
do $$ begin
  create policy attachments_insert_auth on storage.objects for insert to authenticated with check (bucket_id = 'attachments');
exception when others then null; end $$;
do $$ begin
  create policy attachments_insert_anon on storage.objects for insert to anon with check (bucket_id = 'attachments');
exception when others then null; end $$;
do $$ begin
  create policy attachments_delete_auth on storage.objects for delete to authenticated using (bucket_id = 'attachments');
exception when others then null; end $$;

-- realtime publication (each table guarded)
do $$ begin alter publication supabase_realtime add table public.purchase_requests; exception when others then null; end $$;
do $$ begin alter publication supabase_realtime add table public.purchase_orders; exception when others then null; end $$;
do $$ begin alter publication supabase_realtime add table public.ris_requests; exception when others then null; end $$;
do $$ begin alter publication supabase_realtime add table public.inventory_items; exception when others then null; end $$;
do $$ begin alter publication supabase_realtime add table public.stock_card; exception when others then null; end $$;
do $$ begin alter publication supabase_realtime add table public.reservations; exception when others then null; end $$;
do $$ begin alter publication supabase_realtime add table public.audit_logs; exception when others then null; end $$;

-- audit triggers (recreated cleanly)
drop trigger if exists audit_purchase_requests on public.purchase_requests;
drop trigger if exists audit_purchase_orders on public.purchase_orders;
drop trigger if exists audit_ris_requests on public.ris_requests;
drop trigger if exists audit_inventory_items on public.inventory_items;
drop trigger if exists audit_reservations on public.reservations;
create trigger audit_purchase_requests after insert or update or delete on public.purchase_requests
  for each row execute function public.log_audit();
create trigger audit_purchase_orders after insert or update or delete on public.purchase_orders
  for each row execute function public.log_audit();
create trigger audit_ris_requests after insert or update or delete on public.ris_requests
  for each row execute function public.log_audit();
create trigger audit_inventory_items after insert or update or delete on public.inventory_items
  for each row execute function public.log_audit();
create trigger audit_reservations after insert or update or delete on public.reservations
  for each row execute function public.log_audit();

-- report back
select
  (select count(*) from public.stock_card) as stock_card_rows,
  (select count(*) from public.audit_logs) as audit_rows,
  (select count(*) from storage.buckets where id = 'attachments') as bucket_ok;
