-- ============================================================
-- GSO PRIMS — Phase 17: Cross-system Notification Center
-- Notifications are generated by database triggers, exactly like the
-- existing log_audit() pattern, so no module service code has to change and
-- every event is captured regardless of where the write came from.
-- Run once in the Supabase SQL Editor. Idempotent where practical.
-- ============================================================

-- ---------- table ----------

create sequence if not exists public.notification_id_seq;

create table if not exists public.notifications (
  id text primary key,
  title text not null,
  description text,
  -- Drives the drawer's filter chips: Procurement / Inventory / Facilities /
  -- Energy / Water / Fuel.
  module text not null,
  reference_id text,
  reference_type text,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  created_by text
);

create index if not exists idx_notifications_created on public.notifications (created_at desc);
create index if not exists idx_notifications_unread on public.notifications (is_read, created_at desc);
create index if not exists idx_notifications_module on public.notifications (module);

-- ---------- event → notification ----------

create or replace function public.notify_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new jsonb := case when tg_op = 'DELETE' then null else to_jsonb(new) end;
  v_old jsonb := case when tg_op = 'INSERT' then null else to_jsonb(old) end;
  v_ref jsonb := coalesce(v_new, v_old);
  v_title text;
  v_desc text;
  v_module text;
  v_ref_type text;
  v_ref_id text := v_ref->>'id';
  v_status text := v_new->>'status';
  v_prev_status text := v_old->>'status';
  v_user text := coalesce(
    nullif(current_setting('request.jwt.claims', true), '')::jsonb->>'email',
    'System');
begin
  if tg_table_name = 'purchase_requests' then
    v_module := 'Procurement'; v_ref_type := 'purchase-request';
    if tg_op = 'INSERT' then
      v_title := 'New Purchase Request Submitted';
      v_desc := (v_ref->>'pr_number') || ' — ' || coalesce(v_ref->>'purpose', 'No purpose stated');
    elsif tg_op = 'UPDATE' and v_status is distinct from v_prev_status then
      if v_status = 'Approved' then
        v_title := 'Purchase Request Approved';
        v_desc := (v_ref->>'pr_number') || ' was approved.';
      elsif v_status = 'Rejected' then
        v_title := 'Purchase Request Rejected';
        v_desc := (v_ref->>'pr_number') || ' was rejected.';
      end if;
    end if;

  elsif tg_table_name = 'purchase_orders' then
    v_module := 'Procurement'; v_ref_type := 'purchase-order';
    if tg_op = 'INSERT' then
      v_title := 'Purchase Order Created';
      v_desc := (v_ref->>'po_number') || ' created from ' || coalesce(v_ref->>'pr_number', '—');
    elsif tg_op = 'UPDATE' and v_status is distinct from v_prev_status and v_status = 'Approved' then
      v_title := 'Purchase Order Approved';
      v_desc := (v_ref->>'po_number') || ' was approved.';
    end if;

  elsif tg_table_name = 'ris_requests' then
    v_module := 'Procurement'; v_ref_type := 'ris';
    if tg_op = 'UPDATE' and v_status is distinct from v_prev_status and v_status = 'Released' then
      v_title := 'RIS Released';
      v_desc := (v_ref->>'ris_number') || ' has been released.';
    end if;

  elsif tg_table_name = 'inventory_items' then
    v_module := 'Inventory'; v_ref_type := 'inventory';
    if tg_op = 'UPDATE'
       and (v_new->>'on_hand')::numeric <= (v_new->>'reorder_level')::numeric
       and (v_old->>'on_hand')::numeric > (v_old->>'reorder_level')::numeric then
      v_title := 'Low Stock Alert';
      v_desc := (v_ref->>'name') || ' fell to ' || (v_new->>'on_hand') || ' ' ||
                coalesce(v_ref->>'unit', 'units') || ' (reorder at ' || (v_new->>'reorder_level') || ').';
    elsif tg_op = 'DELETE' then
      -- Inventory has no archive state; removal is the closest equivalent.
      v_title := 'Inventory Item Removed';
      v_desc := (v_ref->>'item_code') || ' — ' || (v_ref->>'name') || ' was removed.';
    end if;

  elsif tg_table_name = 'reservations' then
    v_module := 'Facilities'; v_ref_type := 'reservation';
    if tg_op = 'INSERT' then
      v_title := 'Facility Reservation Submitted';
      v_desc := (v_ref->>'res_number') || ' — ' || coalesce(v_ref->>'purpose', 'No purpose stated');
    elsif tg_op = 'UPDATE' and v_status is distinct from v_prev_status then
      if v_status = 'Approved' then
        v_title := 'Facility Reservation Approved';
        v_desc := (v_ref->>'res_number') || ' was approved.';
      elsif v_status = 'Rejected' then
        v_title := 'Facility Reservation Rejected';
        v_desc := (v_ref->>'res_number') || ' was rejected.';
      end if;
    end if;

  elsif tg_table_name = 'energy_bills' and tg_op = 'INSERT' then
    v_module := 'Energy'; v_ref_type := 'energy';
    v_title := 'Energy Bill Added';
    v_desc := 'A monthly electricity bill of PHP ' || (v_ref->>'amount') ||
              ' was recorded for ' || (v_ref->>'billing_month') || '/' || (v_ref->>'billing_year') || '.';

  elsif tg_table_name = 'energy_submeters' and tg_op = 'INSERT' then
    v_module := 'Energy'; v_ref_type := 'energy';
    v_title := 'New Energy Submeter Created';
    v_desc := (v_ref->>'submeter_number') || ' — ' || (v_ref->>'submeter_name') || '.';

  elsif tg_table_name = 'water_bills' and tg_op = 'INSERT' then
    v_module := 'Water'; v_ref_type := 'water';
    v_title := 'Water Bill Added';
    v_desc := 'A monthly water bill of PHP ' || (v_ref->>'amount') ||
              ' was recorded for ' || (v_ref->>'billing_month') || '/' || (v_ref->>'billing_year') || '.';

  elsif tg_table_name = 'water_meter_readings' and tg_op = 'INSERT' then
    v_module := 'Water'; v_ref_type := 'water';
    v_title := 'Water Meter Reading Added';
    v_desc := 'Reading on ' || (v_ref->>'reading_date') || ' — ' ||
              (v_ref->>'consumption') || ' m3 consumed.';

  elsif tg_table_name = 'water_submeters' and tg_op = 'INSERT' then
    v_module := 'Water'; v_ref_type := 'water';
    v_title := 'New Water Submeter Created';
    v_desc := (v_ref->>'submeter_number') || ' — ' || (v_ref->>'submeter_name') || '.';

  elsif tg_table_name = 'fuel_transactions' and tg_op = 'INSERT' then
    v_module := 'Fuel'; v_ref_type := 'fuel';
    v_title := 'Fuel Record Added';
    v_desc := (v_ref->>'liters') || ' L of ' || (v_ref->>'fuel_type') ||
              ' recorded on ' || (v_ref->>'txn_date') || '.';

  elsif tg_table_name = 'fuel_odometer_readings' and tg_op = 'INSERT' then
    v_module := 'Fuel'; v_ref_type := 'fuel';
    v_title := 'Odometer Reading Added';
    v_desc := 'Reading on ' || (v_ref->>'reading_date') || ' — ' ||
              (v_ref->>'distance') || ' km travelled.';
  end if;

  -- Events that do not map to a notification fall through silently.
  if v_title is null then
    return coalesce(new, old);
  end if;

  insert into public.notifications
    (id, title, description, module, reference_id, reference_type, is_read, created_at, created_by)
  values (
    'NTF-' || to_char(now(), 'YYYY') || '-' ||
      lpad(nextval('public.notification_id_seq')::text, 6, '0'),
    v_title, v_desc, v_module, v_ref_id, v_ref_type, false, now(), v_user);

  return coalesce(new, old);
end;
$$;

-- ---------- triggers ----------

drop trigger if exists notify_purchase_requests on public.purchase_requests;
drop trigger if exists notify_purchase_orders on public.purchase_orders;
drop trigger if exists notify_ris_requests on public.ris_requests;
drop trigger if exists notify_inventory_items on public.inventory_items;
drop trigger if exists notify_reservations on public.reservations;
drop trigger if exists notify_energy_bills on public.energy_bills;
drop trigger if exists notify_energy_submeters on public.energy_submeters;
drop trigger if exists notify_water_bills on public.water_bills;
drop trigger if exists notify_water_meter_readings on public.water_meter_readings;
drop trigger if exists notify_water_submeters on public.water_submeters;
drop trigger if exists notify_fuel_transactions on public.fuel_transactions;
drop trigger if exists notify_fuel_odometer_readings on public.fuel_odometer_readings;

create trigger notify_purchase_requests after insert or update on public.purchase_requests
  for each row execute function public.notify_event();
create trigger notify_purchase_orders after insert or update on public.purchase_orders
  for each row execute function public.notify_event();
create trigger notify_ris_requests after update on public.ris_requests
  for each row execute function public.notify_event();
create trigger notify_inventory_items after update or delete on public.inventory_items
  for each row execute function public.notify_event();
create trigger notify_reservations after insert or update on public.reservations
  for each row execute function public.notify_event();
create trigger notify_energy_bills after insert on public.energy_bills
  for each row execute function public.notify_event();
create trigger notify_energy_submeters after insert on public.energy_submeters
  for each row execute function public.notify_event();
create trigger notify_water_bills after insert on public.water_bills
  for each row execute function public.notify_event();
create trigger notify_water_meter_readings after insert on public.water_meter_readings
  for each row execute function public.notify_event();
create trigger notify_water_submeters after insert on public.water_submeters
  for each row execute function public.notify_event();
create trigger notify_fuel_transactions after insert on public.fuel_transactions
  for each row execute function public.notify_event();
create trigger notify_fuel_odometer_readings after insert on public.fuel_odometer_readings
  for each row execute function public.notify_event();

-- ---------- row level security ----------

alter table public.notifications enable row level security;

do $$ begin
  create policy auth_all_notifications on public.notifications for all to authenticated using (true) with check (true);
exception when others then null; end $$;

-- ---------- realtime ----------

do $$ begin alter publication supabase_realtime add table public.notifications; exception when others then null; end $$;

-- ---------- seed ----------
-- A short backfill so the centre is not empty on first open: the most recent
-- real records from each module, rendered through the same wording the
-- triggers use.

insert into public.notifications
  (id, title, description, module, reference_id, reference_type, is_read, created_at, created_by)
select
  'NTF-SEED-' || lpad((row_number() over (order by s.created_at desc))::text, 4, '0'),
  s.title, s.description, s.module, s.reference_id, s.reference_type,
  -- Anything older than three days starts read, so the badge is realistic.
  (s.created_at < now() - interval '3 days'),
  s.created_at, 'System'
from (
  -- Each branch is parenthesised: Postgres does not allow a bare
  -- ORDER BY / LIMIT inside a UNION arm.
  (select 'New Purchase Request Submitted' as title,
          pr_number || ' — ' || purpose as description,
          'Procurement' as module, id as reference_id, 'purchase-request' as reference_type,
          created_at
   from public.purchase_requests order by created_at desc limit 6)
  union all
  (select 'Purchase Order Created', po_number || ' created from ' || pr_number,
          'Procurement', id, 'purchase-order', created_at
   from public.purchase_orders order by created_at desc limit 4)
  union all
  (select 'Facility Reservation Submitted', res_number || ' — ' || purpose,
          'Facilities', id, 'reservation', created_at
   from public.reservations order by created_at desc limit 4)
  union all
  (select 'Water Meter Reading Added',
          'Reading on ' || reading_date || ' — ' || consumption || ' m3 consumed.',
          'Water', submeter_id, 'water', created_at
   from public.water_meter_readings order by created_at desc limit 3)
  union all
  (select 'Fuel Record Added',
          liters || ' L of ' || fuel_type || ' recorded on ' || txn_date || '.',
          'Fuel', vehicle_id, 'fuel', created_at
   from public.fuel_transactions order by created_at desc limit 3)
) s
where not exists (select 1 from public.notifications where id like 'NTF-SEED-%');

-- report back
select count(*) as notifications, count(*) filter (where not is_read) as unread
from public.notifications;
